import React from 'react';
import { Milestone } from 'lucide-react';
import DifficultyControl from './DifficultyControl';
import {updateDistanceRange,MIN_DISTANCE,MAX_DISTANCE} from '../../lib/distance-range';
export default function DistanceControl({value,onChange,difficulty,onDifficultyChange}) {
 const updateMin = next => onChange(updateDistanceRange(value,'min',next));
 const updateMax = next => onChange(updateDistanceRange(value,'max',next));
 const left=(value.min-MIN_DISTANCE)/(MAX_DISTANCE-MIN_DISTANCE)*100,right=(value.max-MIN_DISTANCE)/(MAX_DISTANCE-MIN_DISTANCE)*100;
 return <section className="distance-control" aria-label="코스 거리 설정"><div className="distance-heading"><span className="distance-title"><Milestone size={15}/>희망 주행 거리</span><output><strong>{value.min}–{value.max}</strong> km</output></div><div className="distance-fields"><label>최소 거리<div><input type="number" aria-label="최소 거리 입력" min={MIN_DISTANCE} max={MAX_DISTANCE} step="1" value={value.min} onChange={e=>{if(e.target.value)updateMin(e.target.value);}}/> <span>km</span></div></label><span className="distance-separator">~</span><label>최대 거리<div><input type="number" aria-label="최대 거리 입력" min={MIN_DISTANCE} max={MAX_DISTANCE} step="1" value={value.max} onChange={e=>{if(e.target.value)updateMax(e.target.value);}}/> <span>km</span></div></label></div><div className="dual-range"><div className="range-track"/><div className="range-fill" style={{left:`${left}%`,width:`${right-left}%`}}/><input type="range" min={MIN_DISTANCE} max={MAX_DISTANCE} step="1" value={value.min} onChange={e=>updateMin(e.target.value)} aria-label="최소 주행 거리" aria-valuetext={`${value.min}킬로미터`} style={{zIndex:value.min===MAX_DISTANCE?4:2}}/><input type="range" min={MIN_DISTANCE} max={MAX_DISTANCE} step="1" value={value.max} onChange={e=>updateMax(e.target.value)} aria-label="최대 주행 거리" aria-valuetext={`${value.max}킬로미터`}/></div><div className="distance-labels"><span>{MIN_DISTANCE} km</span><span>{MAX_DISTANCE} km</span></div><DifficultyControl value={difficulty} onChange={onDifficultyChange}/></section>;
}
